apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks2-541b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks2-541b"
  template:
    metadata:
      labels:
        app: "aks2-541b"
    spec:
      containers:
        - name: "aks2-541b"
          image: "myown129.azurecr.io/aks2"
          ports:
          - containerPort: 80