apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks2-a117"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks2-a117"
  template:
    metadata:
      labels:
        app: "aks2-a117"
    spec:
      containers:
        - name: "aks2-a117"
          image: "myown128.azurecr.io/aks2"
          ports:
          - containerPort: 80