apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksbaranee-7d12"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksbaranee-7d12"
  template:
    metadata:
      labels:
        app: "aksbaranee-7d12"
    spec:
      containers:
        - name: "aksbaranee-7d12"
          image: "myown123.azurecr.io/aksbaranee"
          ports:
          - containerPort: 80