apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks3-48e8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks3-48e8"
  template:
    metadata:
      labels:
        app: "aks3-48e8"
    spec:
      containers:
        - name: "aks3-48e8"
          image: "myown130.azurecr.io/aks3"
          ports:
          - containerPort: 80