apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks4-36ff"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks4-36ff"
  template:
    metadata:
      labels:
        app: "aks4-36ff"
    spec:
      containers:
        - name: "aks4-36ff"
          image: "myown123.azurecr.io/aks4"
          ports:
          - containerPort: 80