apiVersion: v1
kind: Service
metadata:
    name: "aks2-7abb"
    labels:
        app: "aks2-7abb"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aks2-7abb"