apiVersion: v1
kind: Service
metadata:
    name: "aksbaranee-7d12"
    labels:
        app: "aksbaranee-7d12"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksbaranee-7d12"