apiVersion: v1
kind: Service
metadata:
    name: "aks3-3f4b"
    labels:
        app: "aks3-3f4b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aks3-3f4b"