apiVersion: v1
kind: Service
metadata:
    name: "aks4-2393"
    labels:
        app: "aks4-2393"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aks4-2393"